#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "✓ $ENV_FILE already exists — using current values"
  echo "  To regenerate, delete it and run ./init.sh again"
  exit 0
fi

echo "⚙️  Generating .env with random secrets..."

JWT_SECRET="dd-$(openssl rand -base64 48 | tr -dc 'a-zA-Z0-9' | head -c64)"
POSTGRES_PASSWORD="dd-$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c24)"

# Generate Supabase-compatible JWTs using Python (HMAC-SHA256)
ANON_KEY=$(python3 -c "
import base64, json, hmac, hashlib
header = base64.urlsafe_b64encode(json.dumps({'alg':'HS256','typ':'JWT'}).encode()).rstrip(b'=').decode()
payload = base64.urlsafe_b64encode(json.dumps({'role':'anon','iss':'supabase','iat':1516239022,'exp':1816239022}).encode()).rstrip(b'=').decode()
sig = base64.urlsafe_b64encode(hmac.new(b'$JWT_SECRET', (header+'.'+payload).encode(), hashlib.sha256).digest()).rstrip(b'=').decode()
print(f'{header}.{payload}.{sig}')
")

SERVICE_KEY=$(python3 -c "
import base64, json, hmac, hashlib
header = base64.urlsafe_b64encode(json.dumps({'alg':'HS256','typ':'JWT'}).encode()).rstrip(b'=').decode()
payload = base64.urlsafe_b64encode(json.dumps({'role':'service_role','iss':'supabase','iat':1516239022,'exp':1816239022}).encode()).rstrip(b'=').decode()
sig = base64.urlsafe_b64encode(hmac.new(b'$JWT_SECRET', (header+'.'+payload).encode(), hashlib.sha256).digest()).rstrip(b'=').decode()
print(f'{header}.{payload}.{sig}')
")

ADMIN_EMAIL="admin-$(openssl rand -hex 4)@dokkadesk.com"
ADMIN_PASSWORD=$(openssl rand -base64 12 | tr -dc 'a-zA-Z0-9' | head -c16)

cat > "$ENV_FILE" << EOF
# ============================================================
# DOKKA Desk — Environment Configuration
# Auto-generated by init.sh on $(date)
# ============================================================

# PostgreSQL
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# JWT Secret (used by GoTrue and PostgREST)
JWT_SECRET=$JWT_SECRET

# Site URL
SITE_URL=http://localhost:8080

# Supabase-compatible API keys (auto-generated)
SUPABASE_PUBLISHABLE_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_KEY

# Vite (frontend) configuration
VITE_SUPABASE_URL=http://localhost:8080
VITE_SUPABASE_PUBLISHABLE_KEY=$ANON_KEY

# Admin credentials (auto-generated)
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD
EOF

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║              DOKKA Desk — Admin Credentials                  ║"
echo "║                                                              ║"
printf "║  Email:  %-47s ║\n" "$ADMIN_EMAIL"
printf "║  Pass:   %-47s ║\n" "$ADMIN_PASSWORD"
echo "║                                                              ║"
echo "║  Save these in a password manager. You can create additional ║"
echo "║  admins from the panel (Administración > Usuarios) and then  ║"
echo "║  delete this default admin.                                  ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "✓ $ENV_FILE created"
echo "→ Run 'docker compose up -d' to start the stack."
