/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedTicketsRegistrarRouteImport } from './routes/_authenticated/tickets.registrar'
import { Route as AuthenticatedTicketsListadoRouteImport } from './routes/_authenticated/tickets.listado'
import { Route as AuthenticatedReportesDashboardRouteImport } from './routes/_authenticated/reportes.dashboard'
import { Route as AuthenticatedReportesCasosGeneralesRouteImport } from './routes/_authenticated/reportes.casos-generales'
import { Route as AuthenticatedReportesAuditoriaRouteImport } from './routes/_authenticated/reportes.auditoria'
import { Route as AuthenticatedReportesAccidentesPersonalesRouteImport } from './routes/_authenticated/reportes.accidentes-personales'
import { Route as AuthenticatedAsistenciasMascotasRouteImport } from './routes/_authenticated/asistencias.mascotas'
import { Route as AuthenticatedAsistenciasHogarRouteImport } from './routes/_authenticated/asistencias.hogar'
import { Route as AuthenticatedAsistenciasDentalRouteImport } from './routes/_authenticated/asistencias.dental'
import { Route as AuthenticatedAsistenciasBiciRouteImport } from './routes/_authenticated/asistencias.bici'
import { Route as AuthenticatedAsistenciasAutomotorRouteImport } from './routes/_authenticated/asistencias.automotor'
import { Route as AuthenticatedAdministracionUsuariosRouteImport } from './routes/_authenticated/administracion.usuarios'
import { Route as AuthenticatedAdministracionRolesRouteImport } from './routes/_authenticated/administracion.roles'
import { Route as AuthenticatedAdministracionListasRouteImport } from './routes/_authenticated/administracion.listas'
import { Route as PReporteCgIdRouteImport } from './routes/p.reporte.cg.$id'
import { Route as PReporteApIdRouteImport } from './routes/p.reporte.ap.$id'
import { Route as AuthenticatedReporteCgIdRouteImport } from './routes/_authenticated/reporte.cg.$id'
import { Route as AuthenticatedReporteApIdRouteImport } from './routes/_authenticated/reporte.ap.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsRegistrarRoute =
  AuthenticatedTicketsRegistrarRouteImport.update({
    id: '/tickets/registrar',
    path: '/tickets/registrar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTicketsListadoRoute =
  AuthenticatedTicketsListadoRouteImport.update({
    id: '/tickets/listado',
    path: '/tickets/listado',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportesDashboardRoute =
  AuthenticatedReportesDashboardRouteImport.update({
    id: '/reportes/dashboard',
    path: '/reportes/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportesCasosGeneralesRoute =
  AuthenticatedReportesCasosGeneralesRouteImport.update({
    id: '/reportes/casos-generales',
    path: '/reportes/casos-generales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportesAuditoriaRoute =
  AuthenticatedReportesAuditoriaRouteImport.update({
    id: '/reportes/auditoria',
    path: '/reportes/auditoria',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportesAccidentesPersonalesRoute =
  AuthenticatedReportesAccidentesPersonalesRouteImport.update({
    id: '/reportes/accidentes-personales',
    path: '/reportes/accidentes-personales',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsistenciasMascotasRoute =
  AuthenticatedAsistenciasMascotasRouteImport.update({
    id: '/asistencias/mascotas',
    path: '/asistencias/mascotas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsistenciasHogarRoute =
  AuthenticatedAsistenciasHogarRouteImport.update({
    id: '/asistencias/hogar',
    path: '/asistencias/hogar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsistenciasDentalRoute =
  AuthenticatedAsistenciasDentalRouteImport.update({
    id: '/asistencias/dental',
    path: '/asistencias/dental',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsistenciasBiciRoute =
  AuthenticatedAsistenciasBiciRouteImport.update({
    id: '/asistencias/bici',
    path: '/asistencias/bici',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAsistenciasAutomotorRoute =
  AuthenticatedAsistenciasAutomotorRouteImport.update({
    id: '/asistencias/automotor',
    path: '/asistencias/automotor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracionUsuariosRoute =
  AuthenticatedAdministracionUsuariosRouteImport.update({
    id: '/administracion/usuarios',
    path: '/administracion/usuarios',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracionRolesRoute =
  AuthenticatedAdministracionRolesRouteImport.update({
    id: '/administracion/roles',
    path: '/administracion/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdministracionListasRoute =
  AuthenticatedAdministracionListasRouteImport.update({
    id: '/administracion/listas',
    path: '/administracion/listas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PReporteCgIdRoute = PReporteCgIdRouteImport.update({
  id: '/p/reporte/cg/$id',
  path: '/p/reporte/cg/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PReporteApIdRoute = PReporteApIdRouteImport.update({
  id: '/p/reporte/ap/$id',
  path: '/p/reporte/ap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReporteCgIdRoute =
  AuthenticatedReporteCgIdRouteImport.update({
    id: '/reporte/cg/$id',
    path: '/reporte/cg/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReporteApIdRoute =
  AuthenticatedReporteApIdRouteImport.update({
    id: '/reporte/ap/$id',
    path: '/reporte/ap/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/administracion/listas': typeof AuthenticatedAdministracionListasRoute
  '/administracion/roles': typeof AuthenticatedAdministracionRolesRoute
  '/administracion/usuarios': typeof AuthenticatedAdministracionUsuariosRoute
  '/asistencias/automotor': typeof AuthenticatedAsistenciasAutomotorRoute
  '/asistencias/bici': typeof AuthenticatedAsistenciasBiciRoute
  '/asistencias/dental': typeof AuthenticatedAsistenciasDentalRoute
  '/asistencias/hogar': typeof AuthenticatedAsistenciasHogarRoute
  '/asistencias/mascotas': typeof AuthenticatedAsistenciasMascotasRoute
  '/reportes/accidentes-personales': typeof AuthenticatedReportesAccidentesPersonalesRoute
  '/reportes/auditoria': typeof AuthenticatedReportesAuditoriaRoute
  '/reportes/casos-generales': typeof AuthenticatedReportesCasosGeneralesRoute
  '/reportes/dashboard': typeof AuthenticatedReportesDashboardRoute
  '/tickets/listado': typeof AuthenticatedTicketsListadoRoute
  '/tickets/registrar': typeof AuthenticatedTicketsRegistrarRoute
  '/reporte/ap/$id': typeof AuthenticatedReporteApIdRoute
  '/reporte/cg/$id': typeof AuthenticatedReporteCgIdRoute
  '/p/reporte/ap/$id': typeof PReporteApIdRoute
  '/p/reporte/cg/$id': typeof PReporteCgIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/': typeof AuthenticatedIndexRoute
  '/administracion/listas': typeof AuthenticatedAdministracionListasRoute
  '/administracion/roles': typeof AuthenticatedAdministracionRolesRoute
  '/administracion/usuarios': typeof AuthenticatedAdministracionUsuariosRoute
  '/asistencias/automotor': typeof AuthenticatedAsistenciasAutomotorRoute
  '/asistencias/bici': typeof AuthenticatedAsistenciasBiciRoute
  '/asistencias/dental': typeof AuthenticatedAsistenciasDentalRoute
  '/asistencias/hogar': typeof AuthenticatedAsistenciasHogarRoute
  '/asistencias/mascotas': typeof AuthenticatedAsistenciasMascotasRoute
  '/reportes/accidentes-personales': typeof AuthenticatedReportesAccidentesPersonalesRoute
  '/reportes/auditoria': typeof AuthenticatedReportesAuditoriaRoute
  '/reportes/casos-generales': typeof AuthenticatedReportesCasosGeneralesRoute
  '/reportes/dashboard': typeof AuthenticatedReportesDashboardRoute
  '/tickets/listado': typeof AuthenticatedTicketsListadoRoute
  '/tickets/registrar': typeof AuthenticatedTicketsRegistrarRoute
  '/reporte/ap/$id': typeof AuthenticatedReporteApIdRoute
  '/reporte/cg/$id': typeof AuthenticatedReporteCgIdRoute
  '/p/reporte/ap/$id': typeof PReporteApIdRoute
  '/p/reporte/cg/$id': typeof PReporteCgIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/administracion/listas': typeof AuthenticatedAdministracionListasRoute
  '/_authenticated/administracion/roles': typeof AuthenticatedAdministracionRolesRoute
  '/_authenticated/administracion/usuarios': typeof AuthenticatedAdministracionUsuariosRoute
  '/_authenticated/asistencias/automotor': typeof AuthenticatedAsistenciasAutomotorRoute
  '/_authenticated/asistencias/bici': typeof AuthenticatedAsistenciasBiciRoute
  '/_authenticated/asistencias/dental': typeof AuthenticatedAsistenciasDentalRoute
  '/_authenticated/asistencias/hogar': typeof AuthenticatedAsistenciasHogarRoute
  '/_authenticated/asistencias/mascotas': typeof AuthenticatedAsistenciasMascotasRoute
  '/_authenticated/reportes/accidentes-personales': typeof AuthenticatedReportesAccidentesPersonalesRoute
  '/_authenticated/reportes/auditoria': typeof AuthenticatedReportesAuditoriaRoute
  '/_authenticated/reportes/casos-generales': typeof AuthenticatedReportesCasosGeneralesRoute
  '/_authenticated/reportes/dashboard': typeof AuthenticatedReportesDashboardRoute
  '/_authenticated/tickets/listado': typeof AuthenticatedTicketsListadoRoute
  '/_authenticated/tickets/registrar': typeof AuthenticatedTicketsRegistrarRoute
  '/_authenticated/reporte/ap/$id': typeof AuthenticatedReporteApIdRoute
  '/_authenticated/reporte/cg/$id': typeof AuthenticatedReporteCgIdRoute
  '/p/reporte/ap/$id': typeof PReporteApIdRoute
  '/p/reporte/cg/$id': typeof PReporteCgIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracion'
    | '/administracion/listas'
    | '/administracion/roles'
    | '/administracion/usuarios'
    | '/asistencias/automotor'
    | '/asistencias/bici'
    | '/asistencias/dental'
    | '/asistencias/hogar'
    | '/asistencias/mascotas'
    | '/reportes/accidentes-personales'
    | '/reportes/auditoria'
    | '/reportes/casos-generales'
    | '/reportes/dashboard'
    | '/tickets/listado'
    | '/tickets/registrar'
    | '/reporte/ap/$id'
    | '/reporte/cg/$id'
    | '/p/reporte/ap/$id'
    | '/p/reporte/cg/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/configuracion'
    | '/'
    | '/administracion/listas'
    | '/administracion/roles'
    | '/administracion/usuarios'
    | '/asistencias/automotor'
    | '/asistencias/bici'
    | '/asistencias/dental'
    | '/asistencias/hogar'
    | '/asistencias/mascotas'
    | '/reportes/accidentes-personales'
    | '/reportes/auditoria'
    | '/reportes/casos-generales'
    | '/reportes/dashboard'
    | '/tickets/listado'
    | '/tickets/registrar'
    | '/reporte/ap/$id'
    | '/reporte/cg/$id'
    | '/p/reporte/ap/$id'
    | '/p/reporte/cg/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/configuracion'
    | '/_authenticated/'
    | '/_authenticated/administracion/listas'
    | '/_authenticated/administracion/roles'
    | '/_authenticated/administracion/usuarios'
    | '/_authenticated/asistencias/automotor'
    | '/_authenticated/asistencias/bici'
    | '/_authenticated/asistencias/dental'
    | '/_authenticated/asistencias/hogar'
    | '/_authenticated/asistencias/mascotas'
    | '/_authenticated/reportes/accidentes-personales'
    | '/_authenticated/reportes/auditoria'
    | '/_authenticated/reportes/casos-generales'
    | '/_authenticated/reportes/dashboard'
    | '/_authenticated/tickets/listado'
    | '/_authenticated/tickets/registrar'
    | '/_authenticated/reporte/ap/$id'
    | '/_authenticated/reporte/cg/$id'
    | '/p/reporte/ap/$id'
    | '/p/reporte/cg/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PReporteApIdRoute: typeof PReporteApIdRoute
  PReporteCgIdRoute: typeof PReporteCgIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/registrar': {
      id: '/_authenticated/tickets/registrar'
      path: '/tickets/registrar'
      fullPath: '/tickets/registrar'
      preLoaderRoute: typeof AuthenticatedTicketsRegistrarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tickets/listado': {
      id: '/_authenticated/tickets/listado'
      path: '/tickets/listado'
      fullPath: '/tickets/listado'
      preLoaderRoute: typeof AuthenticatedTicketsListadoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes/dashboard': {
      id: '/_authenticated/reportes/dashboard'
      path: '/reportes/dashboard'
      fullPath: '/reportes/dashboard'
      preLoaderRoute: typeof AuthenticatedReportesDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes/casos-generales': {
      id: '/_authenticated/reportes/casos-generales'
      path: '/reportes/casos-generales'
      fullPath: '/reportes/casos-generales'
      preLoaderRoute: typeof AuthenticatedReportesCasosGeneralesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes/auditoria': {
      id: '/_authenticated/reportes/auditoria'
      path: '/reportes/auditoria'
      fullPath: '/reportes/auditoria'
      preLoaderRoute: typeof AuthenticatedReportesAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes/accidentes-personales': {
      id: '/_authenticated/reportes/accidentes-personales'
      path: '/reportes/accidentes-personales'
      fullPath: '/reportes/accidentes-personales'
      preLoaderRoute: typeof AuthenticatedReportesAccidentesPersonalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asistencias/mascotas': {
      id: '/_authenticated/asistencias/mascotas'
      path: '/asistencias/mascotas'
      fullPath: '/asistencias/mascotas'
      preLoaderRoute: typeof AuthenticatedAsistenciasMascotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asistencias/hogar': {
      id: '/_authenticated/asistencias/hogar'
      path: '/asistencias/hogar'
      fullPath: '/asistencias/hogar'
      preLoaderRoute: typeof AuthenticatedAsistenciasHogarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asistencias/dental': {
      id: '/_authenticated/asistencias/dental'
      path: '/asistencias/dental'
      fullPath: '/asistencias/dental'
      preLoaderRoute: typeof AuthenticatedAsistenciasDentalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asistencias/bici': {
      id: '/_authenticated/asistencias/bici'
      path: '/asistencias/bici'
      fullPath: '/asistencias/bici'
      preLoaderRoute: typeof AuthenticatedAsistenciasBiciRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/asistencias/automotor': {
      id: '/_authenticated/asistencias/automotor'
      path: '/asistencias/automotor'
      fullPath: '/asistencias/automotor'
      preLoaderRoute: typeof AuthenticatedAsistenciasAutomotorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracion/usuarios': {
      id: '/_authenticated/administracion/usuarios'
      path: '/administracion/usuarios'
      fullPath: '/administracion/usuarios'
      preLoaderRoute: typeof AuthenticatedAdministracionUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracion/roles': {
      id: '/_authenticated/administracion/roles'
      path: '/administracion/roles'
      fullPath: '/administracion/roles'
      preLoaderRoute: typeof AuthenticatedAdministracionRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/administracion/listas': {
      id: '/_authenticated/administracion/listas'
      path: '/administracion/listas'
      fullPath: '/administracion/listas'
      preLoaderRoute: typeof AuthenticatedAdministracionListasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/p/reporte/cg/$id': {
      id: '/p/reporte/cg/$id'
      path: '/p/reporte/cg/$id'
      fullPath: '/p/reporte/cg/$id'
      preLoaderRoute: typeof PReporteCgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/reporte/ap/$id': {
      id: '/p/reporte/ap/$id'
      path: '/p/reporte/ap/$id'
      fullPath: '/p/reporte/ap/$id'
      preLoaderRoute: typeof PReporteApIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reporte/cg/$id': {
      id: '/_authenticated/reporte/cg/$id'
      path: '/reporte/cg/$id'
      fullPath: '/reporte/cg/$id'
      preLoaderRoute: typeof AuthenticatedReporteCgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reporte/ap/$id': {
      id: '/_authenticated/reporte/ap/$id'
      path: '/reporte/ap/$id'
      fullPath: '/reporte/ap/$id'
      preLoaderRoute: typeof AuthenticatedReporteApIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdministracionListasRoute: typeof AuthenticatedAdministracionListasRoute
  AuthenticatedAdministracionRolesRoute: typeof AuthenticatedAdministracionRolesRoute
  AuthenticatedAdministracionUsuariosRoute: typeof AuthenticatedAdministracionUsuariosRoute
  AuthenticatedAsistenciasAutomotorRoute: typeof AuthenticatedAsistenciasAutomotorRoute
  AuthenticatedAsistenciasBiciRoute: typeof AuthenticatedAsistenciasBiciRoute
  AuthenticatedAsistenciasDentalRoute: typeof AuthenticatedAsistenciasDentalRoute
  AuthenticatedAsistenciasHogarRoute: typeof AuthenticatedAsistenciasHogarRoute
  AuthenticatedAsistenciasMascotasRoute: typeof AuthenticatedAsistenciasMascotasRoute
  AuthenticatedReportesAccidentesPersonalesRoute: typeof AuthenticatedReportesAccidentesPersonalesRoute
  AuthenticatedReportesAuditoriaRoute: typeof AuthenticatedReportesAuditoriaRoute
  AuthenticatedReportesCasosGeneralesRoute: typeof AuthenticatedReportesCasosGeneralesRoute
  AuthenticatedReportesDashboardRoute: typeof AuthenticatedReportesDashboardRoute
  AuthenticatedTicketsListadoRoute: typeof AuthenticatedTicketsListadoRoute
  AuthenticatedTicketsRegistrarRoute: typeof AuthenticatedTicketsRegistrarRoute
  AuthenticatedReporteApIdRoute: typeof AuthenticatedReporteApIdRoute
  AuthenticatedReporteCgIdRoute: typeof AuthenticatedReporteCgIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdministracionListasRoute:
    AuthenticatedAdministracionListasRoute,
  AuthenticatedAdministracionRolesRoute: AuthenticatedAdministracionRolesRoute,
  AuthenticatedAdministracionUsuariosRoute:
    AuthenticatedAdministracionUsuariosRoute,
  AuthenticatedAsistenciasAutomotorRoute:
    AuthenticatedAsistenciasAutomotorRoute,
  AuthenticatedAsistenciasBiciRoute: AuthenticatedAsistenciasBiciRoute,
  AuthenticatedAsistenciasDentalRoute: AuthenticatedAsistenciasDentalRoute,
  AuthenticatedAsistenciasHogarRoute: AuthenticatedAsistenciasHogarRoute,
  AuthenticatedAsistenciasMascotasRoute: AuthenticatedAsistenciasMascotasRoute,
  AuthenticatedReportesAccidentesPersonalesRoute:
    AuthenticatedReportesAccidentesPersonalesRoute,
  AuthenticatedReportesAuditoriaRoute: AuthenticatedReportesAuditoriaRoute,
  AuthenticatedReportesCasosGeneralesRoute:
    AuthenticatedReportesCasosGeneralesRoute,
  AuthenticatedReportesDashboardRoute: AuthenticatedReportesDashboardRoute,
  AuthenticatedTicketsListadoRoute: AuthenticatedTicketsListadoRoute,
  AuthenticatedTicketsRegistrarRoute: AuthenticatedTicketsRegistrarRoute,
  AuthenticatedReporteApIdRoute: AuthenticatedReporteApIdRoute,
  AuthenticatedReporteCgIdRoute: AuthenticatedReporteCgIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PReporteApIdRoute: PReporteApIdRoute,
  PReporteCgIdRoute: PReporteCgIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
